instance_name       = "dev-postgres-instance"
db_name             = "devdb"
vpc_id              = "vpc-09b6392xx"
subnet_ids          = ["subnet-03a2f198533c3xxx", "subnet-0f0a816eae6xx"]
security_group_name = "dev-rds-postgres-sg"
allocated_storage   = 10
engine_name         = "postgres"
engine_version      = "18.2"
db_class            = "db.t3.micro"
